# Generated by Django 6.0.4 on 2026-04-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_base',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='permite_mayor',
            field=models.BooleanField(default=False, help_text='Marcar si el producto puede venderse al por mayor (cantidad grande con precio especial)'),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si no se especifica, usa el precio del producto', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TipoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Color, Tamaño, Tipo', max_length=100)),
                ('obligatorio', models.BooleanField(default=False, help_text='¿El cliente debe elegir esta variante?')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_variante', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Tipo de variante',
                'verbose_name_plural': 'Tipos de variante',
            },
        ),
        migrations.CreateModel(
            name='OpcionVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Rojo, A4, Rayado', max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0, help_text='Precio adicional sobre el precio base (0 = sin costo extra)', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogo.tipovariante')),
            ],
            options={
                'verbose_name': 'Opción de variante',
                'verbose_name_plural': 'Opciones de variante',
            },
        ),
    ]
