# Generated by Django 5.1.15 on 2026-05-22 03:31

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_terminobusqueda'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='terminobusqueda',
            index=django.contrib.postgres.indexes.GinIndex(fields=['termino'], name='termino_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
