# Generated by Django 6.0.4 on 2026-04-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_dni',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
