# Generated by Django 5.1.15 on 2026-05-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
